name = "NamedVectors"
uuid = "de74ae39-0789-4cb6-944d-980e42a01a27"
authors = ["Ruben Gonzalez <ruben.carbonbased@gmail.com> and contributors"]
version = "0.0.1"

[deps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
StaticArrays = "1.9.13"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
